### ISSUE TITLE
Do you have plans to do same for Kotlin?

### ISSUE THREAD

**Issue by gimlet2** [Netflix/rewrite#6]

**Comment by jkschneider** [comment]
Somewhat ironic that it is written in Kotlin but targets Java source code? Unfortunately, Kotlin support isn't on the immediate horizon, for strictly pragmatic reasons. The image below will give you a sense of the relative sizes of JVM languages in use at Netflix. While Kotlin is certainly growing, Groovy would probably be the responsible next supported language if any.

![image](https://cloud.githubusercontent.com/assets/1697736/22441086/c2efa2d2-e6ea-11e6-863a-47c199864685.png)

**Comment by orangy** [comment]
I'm curious if the relative size of Kotlin code changed since this was posted? :)

**Comment by jkschneider** [comment]
Certainly has :). It would be nice to have a similar tool for Kotlin. Of course, JetBrains already has all the pieces to do this right? Just need a friendly programmatic API?

**Comment by damianw** [comment]
Came across this issue and I am also curious - @jkschneider do you happen to have an updated infographic for what JVM languages Netflix is using these days? 🙃
