### ISSUE TITLE
[question] how to save code after refactor

### ISSUE THREAD

**Issue by foxundermoon** [Netflix/rewrite#8]
call `diff` can get the diff string
call `fix` can get the  `Tr.CompilationUnit` 
i am read all the doc but can not found any  method to save refactored code.

**Comment by foxundermoon** [comment]
i am found at `rewrite-gradle` module
`Tr.CompilationUnit.print()`

**Comment by jkschneider** [comment]
I'll should be resurrecting and completing the gradle plugin shortly, but looks like you found the relevant bit:

```
Tr.CompilationUnit original = ... // parse some source code
Refactor r = ... // do some refactoring
Tr.Compilation fixed = r.fix(); // now we have a copy of the original AST with the changes applied.
String fixedSource = fixed.print(); // this gives you a String with the entire source file, style preserved!
```

What you do with that String is up to you... you can simply open a `FileOutputStream` and write it straight to the source path if you'd like.
