### ISSUE TITLE
Relationship between entities

### ISSUE THREAD

**Issue by fcostasilva** [Netflix/rewrite#9]
Is there a way to serialize several correlated java files into a single file/json output? What I'm looking for is an output that is organized in such a way that correlated entities refer to each other, instead of having several "solo" representations.

**Comment by jkschneider** [comment]
Can you provide a concrete example of what you are trying to do? I can imagine a couple things you might be asking but can't be sure.

**Comment by fcostasilva** [comment]
Sorry for the unclear question. For now, I'm concerned about the JSON serialization only, but it may also be relevant for other types of serializations. Consider the code below:

`List<CompilationUnit> units = parser.parse(myFiles);`

From what I understand, if I try to serialize compilation units one by one, references such as method calls will be mapped in a completely independent manner, instead of serialized in a way like " I'm A, calling the method foo, from the class ref_B_whatever". Even when you explicitly says the classes are dependent, the serialization doesn't take into account that B is an external class, with its own representation:

```
        String a = "class A {{ B.foo(0); }}";
        String b = "class B { static void foo(int n) {} }";

        Tr.CompilationUnit cu = parser.parse(a, /* which depends on */ b);
```

The JSON result is presented in the following image. Notice that both id and ref generated values seem to be locally valid only. 

![rewrite_json_serialization](https://cloud.githubusercontent.com/assets/7120328/25049010/d53a4822-213f-11e7-8a4a-5c70343e86ad.png)

**Comment by jkschneider** [comment]
Gotcha. This behavior is simply an artifact of us using Jackson's `@JsonIdentityInfo` to only serialize a full object the first time it appears, and references thereafter.

I'm guessing if you used Jackson to instead serialize a `List<Tr.CompilationUnit>` rather than iterating over each element of the list and serializing one at a time, you may get the behavior you desire?

**Comment by jkschneider** [comment]
Also, if it's helpful: we were using the Smile format as configured in `rewrite-jackson` to serialize at Netflix, since the end result is quite a bit smaller.
